export enum ErrorCode {
  MATCH_NOT_FOUND = 'MATCH_NOT_FOUND',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  NOT_SUBSCRIBED = 'NOT_SUBSCRIBED',
  RATE_LIMITED = 'RATE_LIMITED',
  MESSAGE_TOO_LONG = 'MESSAGE_TOO_LONG',
  EMPTY_MESSAGE = 'EMPTY_MESSAGE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
